# Generated by Django 3.0.6 on 2020-05-27 05:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_auto_20200527_0531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 27, 5, 50, 57, 657627, tzinfo=utc)),
        ),
    ]
